---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: ['--remove']
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: check-json
  - repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8
        args: ['--max-line-length=120']
  - repo: https://github.com/FalconSocial/pre-commit-python-sorter
    rev: master
    hooks:
      - id: python-import-sorter
        args: ['--silent-overwrite']
  - repo: https://github.com/chewse/pre-commit-mirrors-pydocstyle
    rev: master
    hooks:
      - id: pydocstyle
        args: ['--config=.pydocstyle', '--match="(?!test_).*\.py"']
